### ISSUE TITLE
This throws an error 

### ISSUE THREAD

**Issue by Nexengineer** [bsneha90/WebViewLocalHtml#1]
Hi, 

Your code gives error some thing like below.
<img width="451" alt="screen shot 2018-05-09 at 3 57 38 pm" src="https://user-images.githubusercontent.com/16309506/39810189-bae08d3e-53a1-11e8-90bd-c52517932639.png">

**Comment by bsneha90** [comment]
Hi @Nexengineer were you running in the debug mode?

**Comment by bsneha90** [comment]
Hi @Nexengineer the issue was on ios, thanks for pointing out. Have fixed and checked in.

**Comment by Nexengineer** [comment]
Thanks
